name: make-lint
on: 
  - push
jobs:
  make-lint-job:
    
    runs-on: ubuntu-latest

    strategy:

    matrix: 
      node-version: [17.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
     with:
        node-version: ${{ matrix.node-version }}
      - name: make-install-step
        run: |
         make install

         env: 
         CI: true
      - name: make-lint-step
        run: |
         make lint

         - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v2.7.4
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
